on:
  push:
    branches:
      - master
jobs:
  affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'
      - run: npm ci
      - name: Build Affected Projects
        run: npx nx affected:build --base=master~1 --head=HEAD
      - name: Test Affected Projects
        run: npx nx affected:test --base=master~1 --head=HEAD
      - name: Deploy Affected Projects
        run: npx nx affected:deploy --base=master~1 --head=HEAD